### ISSUE TITLE
Play framework evolutions

### ISSUE THREAD

**Issue by amirkarimi** [lastland/scala-forklift#17]
How is it possible to use forklift with Play framework evolutions?

**Comment by lastland** [comment]
Hi @AmirKarimi , I'm not familiar with Play framework but I'm going to take a look at it. I will try to get back to this issue soon.

**Comment by lastland** [comment]
Hi @AmirKarimi, I have made an example of using Play, Play-Slick, with Forklift. You can check it out here: https://github.com/lastland/play-slick-forklift-example You can also find some explanations here: https://github.com/lastland/play-slick-forklift-example/blob/master/README.markdown

Basically you don't need much extra work to start a web application with Play, Play-Slick, and Forklift. Just clone the Forklift start template from https://github.com/lastland/scala-forklift-start-template, put the web application written with Play under the `app` directory, and edit some files accordingly (for example, edit [`migrations/src/main/scala/Migrations.scala`](https://github.com/lastland/play-slick-forklift-example/blob/master/migrations/src/main/scala/Migrations.scala) to tell Forklift where to read the database configurations).

Please let me know if you have any questions or suggestions.
