### ISSUE TITLE
"build.scala" is deprecated

### ISSUE THREAD

**Issue by DerLump** [lastland/scala-forklift#19]
@lastland Hi,
thanks a lot, "Scala-Forklift" is really great!

I have one suggestion, the "build.scala" is deprecated now as far as I know.
I would suggest to only use the "build.sbt" for the template and the example. It also works with the sub-projects, I tried it already.
If you agree, I can make a commit for both of them.

Have a nice day!

**Comment by lastland** [comment]
Hi @DerLump,

Thanks for reporting for this! I'm glad that you like Scala-Forklift.

I will look into this issue. And a pull request is always welcome if you are willing to contribute! 😃

**Comment by lastland** [comment]
@DerLump, would you mind telling me where I can find the official announcement of deprecating "build.scala"?

**Comment by DerLump** [comment]
@lastland thanks for your answer!
This is a merged pull request of "sbt": [https://github.com/sbt/sbt/pull/2524](https://github.com/sbt/sbt/pull/2524) it says, that the "Build.scala" is removed from the common classpath.

This is a "Google Groups" discussion about the deprecation of the "Build.scala" file: [https://groups.google.com/forum/#!topic/sbt-dev/S-pr2nZQ3KY](https://groups.google.com/forum/#!topic/sbt-dev/S-pr2nZQ3KY)

Here: [http://www.scala-sbt.org/1.0/docs/Full-Def.html](http://www.scala-sbt.org/1.0/docs/Full-Def.html) it tells you right at the beginning: "This page describes an old style of .scala build definition. In the previous versions of sbt, .scala was the only way to create multi-project build definition, but sbt 0.13 added multi-project .sbt build definition, which is the recommended style."

Or in this video: [https://www.parleys.com/tutorial/road-sbt-1-0-paved-server-1](https://www.parleys.com/tutorial/road-sbt-1-0-paved-server-1) around 30:00:00, they talk about it.

I'm not quite sure if it is deprecated already, but at least it seems like it's gonna be deprecated soon.

I will do a pull request as soon as possible, thank you! :)

**Comment by lastland** [comment]
Thanks for the links!

I will keep this issue open for now because the file `project\build.scala` also needs to be replaced.
