### ISSUE TITLE
Change License to Apache 2.0

### ISSUE THREAD

**Issue by lastland** [lastland/scala-forklift#23]
@cvogt suggests that we may want to consider changing the license to Apache 2.0 (our current license is BSD).

For the major difference between two licenses, here's a comment from @fommil, and I quote:

> Apache is definitely not more restrictive, it's safer. The primary difference is that nobody can contribute their patented work to the project without also giving a free licence to all future users. 
> (from https://github.com/cvogt/cbt/issues/27)

For more information you can check his talk here: http://fommil.github.io/scalasphere16/

I would like to see if our other contributors (cc @kshepard @DerLump) agree with this change?

**Comment by kshepard** [comment]
Sounds good to me.
