### ISSUE TITLE
Scala 2.12 Support

### ISSUE THREAD

**Issue by totallymike** [lastland/scala-forklift#30]
Hi there.  This library looks like exactly what we'd like to use to manage our Slick migrations. Is it possible to push a build for Scala 2.12?

Thank you very much!

**Comment by lastland** [comment]
Hi,

I would definitely like to push a build for Scala 2.12. One problem right now is that not all Scala-Forklift's dependencies have a build for Scala 2.12 (for example, [slick-migration-api](https://github.com/nafg/slick-migration-api) does not). 

However, I will try to figure out a way as soon as possible.

**Comment by totallymike** [comment]
Makes sense! I appreciate your efforts. For what it's worth, we're particularly interested in the version that supports slick 3.2.0-M2.  For the time being I was able to build jars manually.

**Comment by cvogt** [comment]
@nafg may be able to help porting slick-migration-api

**Comment by nafg** [comment]
https://github.com/nafg/slick-migration-api/pull/12

**Comment by totallymike** [comment]
Thanks so much to both of you for your work in getting a release out!

**Comment by lastland** [comment]
@nafg I think I have some time to work on this tomorrow and during the weekend. Is it possible that you publish a version for Scala 2.12 soon? It can be just a snapshot version. Thanks!

**Comment by nafg** [comment]
@lastland are you available now for a chat?

**Comment by lastland** [comment]
@nafg How about in 10 minutes? I think you can find me slack?

Edit: Got your message on gitter.

**Comment by nafg** [comment]
@lastland done. https://github.com/nafg/slick-migration-api https://bintray.com/naftoligug/maven/slick-migration-api/0.4.0-M1

**Comment by lastland** [comment]
@nafg Thanks!

**Comment by lastland** [comment]
Scala-Forklift 0.3.0 is published for Scala 2.12. It may take several hours for maven to sync it.

However, I only published it for Scala 2.12 because there are still some problems with Scala 2.11 (see #32 ).
