### ISSUE TITLE
Support Slick 3.3.0

### ISSUE THREAD

**Issue by gsilvestrin** [lastland/scala-forklift#47]
Now that Slick 3.3.0 was [released](http://slick.lightbend.com/news/2019/01/30/slick-3.3.0-released.html) it would be nice to support it. Something especially interesting is the code gen of case classes with more than 22 elements [link](https://github.com/slick/slick/commit/9f946ed421668b10cd00de1df3d83f2111ecede1)

**Comment by lastland** [comment]
Closed by #50 

`0.3.2-SNAPSHOT` now supports Slick 3.3.x and I am in the middle of publishing `0.3.2`.

**Comment by lastland** [comment]
Hi,

Scala-forklift 0.3.2 is now published (note that it may take a while before it appears on Maven) and it supports Scala 2.13 and Slick 3.3.x.

Special thanks to @karolchmist who makes this happen!
