### ISSUE TITLE
Scala 2.13 Support

### ISSUE THREAD

**Issue by francisdb** [lastland/scala-forklift#48]
`2.13` has been out for a while now

will first need #47 implemented, slick `3.3.2` has Scala `2.13` support

**Comment by halfmatthalfcat** [comment]
@lastland any potential movement on this?

**Comment by lastland** [comment]
@halfmatthalfcat @francisdb Hi, sorry for the very late response. I have made some changes to support Scala 2.13 and Slick 3.3.2. Unfortunately, for some reason, the updates cannot pass the MySQL tests on Circle CI so I'm not going to release it yet. The failure in tests could be a bug in my code or my unfamiliarity to new changes that happened in Circle CI. Unfortunately, I would have little time to figure that out this week. I would definitely try to figure the issue out and publish a new version next week. In the meantime, any help would be very welcome and gratefully received (it's in `circleci-20-test` branch).

I'm sorry that I was occupied by other duties that I could not update as frequently. And sadly, although I will try, I am not sure if I will be able to update frequently in the future. I won't be angry if people suggest other alternatives to scala-forklift here. And if you like scala-forklift and would like to become a maintainer, I will be glad to assist.

**Comment by lastland** [comment]
Dear All,

Scala-forklift 0.3.2 is published (note that it may take a while before it appears on Maven) which supports Scala 2.13 and Slick 3.3.x.

Special thanks to @karolchmist who makes this happen!
